config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :companies

  root 'welcome#index'

  get 'contact', to: 'welcome#contact', as: :contact
  get 'about', to:'welcome#about', as: :about
  get 'encuesta', to:'welcome#encuesta', as: :encuesta

  resources :user_practice
  get 'survey', to: 'user_practice#index', as: :survey
  post 'survey', to: 'user_practice#index', as: :survey_withpost
  get 'results', to:'results#index', as: :results

end

app/views/partials/_modals_devise.html.erb
<!-- Login -->
<div id="modalLogin" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="container-modal">
          <%= render :file => 'devise/sessions/new' %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- Login ends -->


<!-- Register-->
<div id="modalRegister" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="container-modal">
          <%= render :file => 'devise/registrations/new' %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- Register ends -->

app/views/partials/_navigation.html.erb
<%= @hola %>
<!--header section-->
<header class="header">
  <!--navigation bar-->
  <nav class="nav navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
          <span class="fa fa-bars"></span>
        </button>
        <a href="/" class="navbar-brand">MAPS</a>
      </div>
      <div class="collapse navbar-collapse navbar-left" id="mynavbar">
        <ul class="nav navbar-nav">
          <li class="active"> <%= link_to "Inicio", root_path %> </li>
          <% if user_signed_in? %>
            <li> <%= link_to "Iniciar método", survey_path, id:"start-method" %> </li>            
            <% if @results_exist %>
              <li> <%= link_to "Resultados", results_path %> </li>
            <% end %>
          <% end %>
          <li> <%= link_to "Acerca del método", about_path %> </li>
          <li> <%= link_to "Contacto", contact_path %> </li>
        </ul>
      </div>
      <!-- User menus -->
      <div class="collapse navbar-collapse navbar-right" id="mynavbar">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="padding:10px;">
                  <img src="<%= current_user.gravatar_url%>" class="img-grav" />
                  <%= current_user.name %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<%= edit_user_registration_path %>"><i class="fa fa-user"></i> &nbsp;Perfil</a></li>
                <li><a href="<%= destroy_user_session_path %>" data-method="delete"><i class="fa fa-sign-out"></i> &nbsp;Salir</a></li>
              </ul>
            </li>
          <% else %>
            <li>
              <a data-toggle="modal" data-target="#modalLogin" href="">Iniciar Sesión</a>
            </li>
          <% end %>
        </ul>
      </div>
      <!-- ends User menus -->
    </div>
  </nav>
  <!--navigation bar ends-->
</header>
<!--header ends-->